title: Victoria Moraes
description: I was born and raised in Mato Grosso do Sul, Brazil. Although it is a heavily pecuarist state, I was always interested in mathematics, music, theatre and technology. In college, I became a member of the choir and fell in love with it. to be continued..Career Goals

baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "https://mr4s.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Victoria Moraes
tagline: Computer Engineering Student
about-description: # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: victoriamoraes42@gmail.com # Add your Email address
facebook: zydrate.gun
#phone: 044 825 5523 # Add your Phone number
#website: artemsheludko.pw # Add your website, do not add http://
linkedin: victória-moraes # Add your Linkedin handle
github: mr4s # Add your Github handle
#twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
