title: Victoria Moraes
description: 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mr4s.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Victoria Moraes
tagline: Computer Science Graduate Student
about-description: Computer Engineer currently living in Campinas, SP and studying to get a master's degree.
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: victoriamoraes42@gmail.com # Add your Email address
facebook: zydrate.gun
#phone: 044 825 5523 # Add your Phone number
#website: artemsheludko.pw # Add your website, do not add http://
linkedin: victoria-moraes # Add your Linkedin handle
github: mr4s # Add your Github handle
#twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
